[package]
name = "war_on_terror"
version = "0.1.0"
authors = ["Alastair Paragas <alastairparagas@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde_json = "1.0"
regex = "1"
